//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBones.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string CarId { get; set; }
    }
}
